export const dispatchActionTypes={
  LOAD_DATA: "LOAD_DATA",
	LOADING_DATA: "LOADING_DATA",
	PRICE_RANGE: "PRICE_RANGE",
	HIGH_TO_LOW: "HIGH_TO_LOW",
	LOW_TO_HIGH: "LOW_TO_HIGH",
	CATEGORY:"CATEGORY",
	RATING: "RATING",
	REMOVE_FILTER:"REMOVE_FILTER",
	CLEAR: "CLEAR",
}